/**
 * Video configuration for Gitgem Explainer Tool
 * 
 * This is the main config file for creating explainer videos.
 * Timeline IDs (S01...) are generated by tts_build.py.
 * Chapter count and titles come from narration.txt `# CHAPTER n title` lines.
 */
export type HudEntry = {fromS: string; toS: string; text: string; tech?: string; fromOffset?: number; toOffset?: number; w?: number};
export type RailSpec = {steps: string[]; switchS: string[]; fromS: string; toS: string};

export const VIDEO = {
  /** Asset directory: public/assets/<slug>/ (audio.wav written by tts_build.py) */
  slug: 'demo',
  
  /** Language: English only (removed Chinese support) */
  lang: 'en' as const,
  
  /** Background: 'dots' dot-field wave (default) | 'stars' star field with fog */
  bg: 'dots' as 'stars' | 'dots',
  
  /** Title configuration */
  title: {
    big: 'YOUR TOPIC',
    rest: '',
    en: 'Your Topic Explained',
    tagline: 'A free explainer video from Gitgem.org'
  },
  
  /** End credit card (shows after content fades to black) */
  credit: null as {kicker: string; title: string; byline: string; note: string} | null,
  
  /** End credit line (default: shows "Presented by Gitgem.org") */
  builtBy: 'Presented by Gitgem.org',
  
  /** Chapter subtitles (shown on chapter cards from chapter 2 onwards) */
  chapterTech: ['Introduction', 'How It Works', 'Deep Dive', 'Getting Started'],
  
  /** Top HUD capsule (current section name) */
  hud: [
    {fromS: 'S01', toS: 'S05', text: 'Introduction', tech: 'Overview'},
    {fromS: 'S06', toS: 'S12', text: 'How It Works', tech: 'Mechanism'},
    {fromS: 'S13', toS: 'S18', text: 'Deep Dive', tech: 'Details'},
    {fromS: 'S19', toS: 'S24', text: 'Getting Started', tech: 'Practical Guide'},
  ] as HudEntry[],
  
  /** Pipeline rail (optional, for step-by-step processes) */
  rails: [] as RailSpec[],
  
  /** Fade duration for ending (frames) */
  endingFade: 30,
};
